version: '3.8'

services:
  resumeai:
    build: .
    ports:
      - "8000:8000"  # Backend API
      - "8501:8501"  # Frontend Web App
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=sqlite:///./resume_optimizer.db
      - MAX_FILE_SIZE_MB=10
      - MAX_RESUMES_PER_UPLOAD=20
    volumes:
      - ./data:/app/data  # Persist data
    restart: unless-stopped

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - resumeai
    restart: unless-stopped
